### ISSUE TITLE
Annotation Schema

### ISSUE THREAD

**Issue by malteos** [malteos/followthemoney#1]
**Requirements**
- Each schema as its own ES index
- Faceted search with filters on annotations (e.g., documents matching TERM with TOPIC)

![Aleph Annotation Schema](https://user-images.githubusercontent.com/7977470/77308735-b6577f00-6cfb-11ea-9915-1f25866d7ddf.png)

## Schema

```yml
Document:
  extends: 
  - Thing
  - Analyzable
  label: File
  plural: Files
  matchable: false
  generated: true
  featured:
  - title
  - fileName
  - mimeType
  - parent
  caption:
  - fileName
  - title
  properties:
    contentHash:
      label: "Checksum"
      description: "SHA1 hash of the data"
      # hidden: true
      type: checksum
    title:
      label: "Title"
      type: string
      rdf: http://purl.org/dc/elements/1.1/title
      caption: true
```

#### Annotations

```yaml
BaseAnnotation:
  abstract: true
  extends: 
  - Interval
  generated: true
  edge:
    source: document
    label: "belongs to"
    target: information
    directed: true
    #caption #???
  properties:
    document:
      label: "Document"
      type: entity
      range: Document
      description: "Annotation belongs to this document"
   information:
     label: "Annotated Information"
     type: entity
     range: AnnotatedInformation

TopicAnnotation:
  extends: 
  - BaseAnnotation
  properties:
       information:
          range: Topic

TranslationAnnotation:
  extends: 
  - BaseAnnotation
  properties:
       information:
          range: Translation

TextPositionAnnotation:
  extends: 
  - BaseAnnotation
  properties:
       information:
          range: TextPosition

NamedEntityAnnotation:
  extends: 
  - TextPositionAnnotation
  properties:
       information:
          range: NamedEntity
```

```yaml
AnnotatedInformation:
  abstract: true
   extends:
   - Thing

Topic:
   extends:
   - AnnotatedInformation

Translation:
   extends:
   - AnnotatedInformation
   properties:
      translatedText: 
        label: Translated text
        type: text
      language:
         label: "Language"
         type: language
         rdf: http://purl.org/dc/terms/language

TextPosition:
   extends:
   - AnnotatedInformation
   properties:
      beginIndex: 
        label: "Begin index (from 0)"
        type: number
      endIndex:
         label: "End index"
         type: number
      anchorText:
         label: "Text from begin to end"
         type: text

NamedEntity:  # better name needed
   extends:
   - TextPosition
   properties:
     entityClass: 
      label: "Class of matched entity (Person, Orga, Location, ...)"
      type: text
```

#### Linked Annotations
```yml

Citation:
   extends:
   - TextPosition
   properties:
     citedDocument: 
      label: "Cited document"
      type: document
```

**Comment by malteos** [comment]
All annotations as flat properties? Properties are always lists?

```yaml

Annotatable:
  label: Annotatable
  plural: Annotatables
  abstract: true
  matchable: false
  generated: true
  properties:
    # translation
    annotatedTranslation:
      label: "Annotated translation"
      type: text
    annotatedTranslationLanguage:
      label: "Language of annotated translation"
      type: language
    # topic
    annotatedTopic:
      label: "Annotated topic"
      type: string
    # citation
    annotatedCitedDocuments:
      label: "Annotated citations from this document to others"
      type: entity
      range: Document
    annotatedCitedDocumentsPosition:
      label: "Position of annotated citations"
      type: json
    annotatedCitingDocuments:
      label: "Annotated citations from other documents to this one"
      type: entity
      range: Document
    # NER
    annotatedEntity:
      label: "Annotated entity"
      type: entity
    annotatedEntitiesAnchor:
      label: "Anchor text of annotated entities"
      type: string
    annotatedEntityPosition:
      label: "Position of annotated entity"
      type: json
    annotatedEntityClass:
      label: "Class of annotated entity"
      type: string
```

## Example
```javascript

doc = {
  "name": "Doc title", 
  # ...
 "annotatedTranslation": ["This is a translation", "Das ist eine Übersetzung"],
 "annotatedTranslationLauage": ["eng", "deu"],

 "annotatedTopic": ["Politics", "Sports"],

 "annotatedCitation": ["<entity id>", "<entity id>"],
 "annotatedCitationPosition": [{"beginIndex": 12, "endIndex": 42}, {"beginIndex": 62, "endIndex": 499}],

 "annotatedEntity": ["<entity id>", "<entity id>"],
 "annotatedEntityAnchor": ["Max Musterman", "Berlin"],
 "annotatedEntityPosition": [{"beginIndex": 12, "endIndex": 42}, {"beginIndex": 62, "endIndex": 499}],
 "annotatedEntity": ["PERSON", "LOCATION"],
};

```
